name: Cache Dependencies Demo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  cache-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: prime-cache-1a8a02a
        id: cache-step
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: cache-1a8a02a

      - name: Show cache result
        run: |
          echo "Cache hit/miss: ${{ steps.cache-step.outputs.cache-hit }}"
