name: Demo Action with Email Step

on:
  workflow_dispatch: # Allows manual triggering
  push:
    branches:
      - main

jobs:
  test-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: 22f1001941@ds.study.iitm.ac.in
        run: echo "Hello, world!"
